name: logmein-host
version: '1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: The LogMeIn Host Software (Beta) for Linux # 79 char long summary
icon: snap/gui/icon.png
base: core18
description: |-
 LogMeIn allows you to access your computers from any device.

 You can connect to a Linux host, in an web-based secure shell and it allows you to send commands to the host computer.

 For more information on LogMeIn for Linux and how to attach your host to your account, try the developer website.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  pytty:
    plugin: python
    source: .
    requirements: [ requirements.txt ]
    stage-packages: [ openssh-client ]
  reverse-proxy:
    source: reverse-proxy/
    plugin: nodejs
    nodejs-package-manager: npm
    build-packages: [ gcc, g++, make, python ]
  novnc:
    plugin: dump
    source: https://github.com/novnc/noVNC/archive/v1.1.0.tar.gz
    organize:
      '*': noVNC/
  novnc-branding:
    plugin: dump
    source: ./remctrl/noVNC-branding
    organize:
      '*': noVNC-branding/
  websockify:
    plugin: nil
    stage-packages: 
      - websockify
      - python-websockify
      - python-setuptools
      - python-numpy
      - python-openssl
      - openssl 
      - net-tools
    organize:
      usr/bin/python2-websockify: usr/bin/websockify

apps:
  pytty:
    command: pytty
    daemon: simple
    restart-condition: always
    plugs: [ network, network-bind, process-control ]
  logmein-host:
    command: logmein_host
    daemon: simple
    restart-condition: always
    plugs: [ network, network-bind, process-control ]
  reverse-proxy:
    command: reverse-proxy
    daemon: simple
    restart-condition: always
    plugs: [ network, network-bind ]
  novnc:
    command: noVNC/utils/launch.sh --vnc localhost:23826 --listen localhost:23825 --web "${SNAP}/noVNC-branding" --cert "${SNAP_COMMON}/self.pem"
    daemon: simple
    restart-condition: always
    plugs: [ network, network-bind, process-control ]
  novnc-login:
    command: noVNC/utils/launch.sh --vnc localhost:23824 --listen localhost:23823 --web "${SNAP}/noVNC-branding" --cert "${SNAP_COMMON}/self.pem"
    daemon: simple
    restart-condition: always
    plugs: [ network, network-bind, process-control ]
