name: logmein-host
version: '1.2.0'
summary: The LogMeIn Host Software (Beta) for Linux
icon: snap/gui/icon.png
base: core18
description: |-
 LogMeIn allows you to access your computers from any device.

 You can connect to a Linux host, in an web-based secure shell and it allows you to send commands to the host computer.

 For more information on LogMeIn for Linux and how to attach your host to your account, try the developer website.

grade: stable
confinement: strict

parts:
  pytty:
    plugin: python
    source: .
    requirements: [ requirements.txt ]
    stage-packages: 
      - openssh-client
      - cmake
      - libssh2-1-dev
      - libssl-dev
      - zlib1g-dev
    override-prime: |
      snapcraftctl prime
      cp $SNAPCRAFT_PROJECT_DIR/setup-vnc.sh $SNAPCRAFT_PRIME/
  reverse-proxy:
    source: reverse-proxy/
    plugin: nodejs
    nodejs-version: 8.17.0
    nodejs-package-manager: yarn
    build-environment:
      - npm_config_unsafe_perm: 'true'
      - npm_config_prefer_online: 'true'
    build-packages: 
      - git
      - python
      - build-essential
  novnc:
    plugin: dump
    source: https://github.com/novnc/noVNC/archive/v1.1.0.tar.gz
    organize:
      '*': noVNC/
  novnc-branding:
    plugin: dump
    source: ./remctrl/noVNC-branding
    organize:
      '*': noVNC-branding/
  websockify:
    plugin: nil
    stage-packages: 
      - websockify
      - python3-websockify
      - python3-setuptools
      - python3-numpy
      - python3-openssl
      - openssl 
      - net-tools
    organize:
      usr/bin/python3-websockify: usr/bin/websockify
  websockify-custom:
    plugin: dump
    source: ./remctrl/websockify-custom
    organize:
      '*': websockify-custom/
  x11vnc:
    plugin: nil
    stage-packages:
      - x11vnc
      - xauth
      - coreutils
  x11vnc-scripts:
    plugin: dump
    source: ./remctrl/scripts
    organize:
      '*': scripts/

apps:
  pytty:
    command: pytty
    daemon: simple
    restart-condition: always
    plugs: [ network, network-bind, process-control ]
  wetty:
    command: wetty --port 23822 --title LogMeIn --base /xterm/ --host 127.0.0.1 --forcessh
    daemon: simple
    restart-condition: always
    plugs: [ network, network-bind, process-control ]
  logmein-host:
    command: logmein_host
    daemon: simple
    restart-condition: always
    plugs: [ network, network-bind, process-control ]
  reverse-proxy:
    command: reverse-proxy
    daemon: simple
    restart-condition: always
    plugs: [ network, network-bind ]
  novnc:
    # The vnc server at localhost:23826 can be overriden if the "use-default-vnc-port" snap config is set to "yes", 
    # so localhost:5900 will be used in this case.
    command: websockify-custom/launch.sh --use-snap-settings --vnc localhost:23826 --listen localhost:23825 --web $SNAP/noVNC-branding --cert $SNAP_COMMON/self.pem
    daemon: simple
    restart-condition: always
    environment:
        PYTHONPATH: ${PYTHONPATH}:${SNAP}/websockify-custom
    plugs: [ network, network-bind, process-control ]
  novnc-login:
    command: websockify-custom/launch.sh --vnc localhost:23824 --listen localhost:23823 --web $SNAP/noVNC-branding --cert $SNAP_COMMON/self.pem
    daemon: simple
    restart-condition: always
    environment:
        PYTHONPATH: ${PYTHONPATH}:${SNAP}/websockify-custom
    plugs: [ network, network-bind, process-control ]
  logmein-vnc:
    command: scripts/logmein-vnc.sh
    plugs: [ network, network-bind, x11 ]
